
/**
 * Google Gemini REST API Client
 * Bypasses Vercel AI SDK validation for audio inputs
 */

interface GoogleGenerationConfig {
    apiKey: string
    model?: string // e.g. "gemini-1.5-flash"
}

export async function transcribeWithGoogleRest(
    base64Audio: string,
    config: GoogleGenerationConfig
): Promise<string> {
    const model = config.model || 'gemini-1.5-flash'
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${config.apiKey}`

    const payload = {
        contents: [{
            parts: [
                {
                    inline_data: {
                        mime_type: "audio/webm",
                        data: base64Audio
                    }
                },
                {
                    text: "Please transcribe this audio. Identify different speakers as 'Speaker 1', 'Speaker 2', etc. if possible. Return only the transcripts."
                }
            ]
        }],
        generationConfig: {
            temperature: 0.2,
            maxOutputTokens: 8192,
        }
    }

    try {
        const response = await fetch(url, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        })

        if (!response.ok) {
            const errorText = await response.text()
            throw new Error(`Google API Error: ${response.status} ${response.statusText} - ${errorText}`)
        }

        const data = await response.json()

        // Extract text from response
        const text = data.candidates?.[0]?.content?.parts?.[0]?.text
        if (!text) {
            throw new Error('No text generated by Google API')
        }

        return text

    } catch (error) {
        console.error('Google REST Transcription failed:', error)
        throw error
    }
}
